/* Konu İçerikleri - 6. Sınıf Ders Notları
   Mini işaretleme: "## başlık" bölüm başlığı, "- madde" madde, düz satır paragraf. */
var DETAY6 = {

/* ===================== TÜRKÇE ===================== */
trk6: [
// 0 Sözcükte Anlam
"## Gerçek, Mecaz ve Terim Anlam\nBir sözcüğün sözlükteki ilk anlamına gerçek anlam denir. Kelimeyi bilinen anlamının dışında kullanırsak mecaz anlam ortaya çıkar.\n- Gerçek anlam: \"Ayağım çok ağrıyor.\" (vücudumuzun bölümü)\n- Mecaz anlam: \"Bugün ağır bir ders işledik.\" (zor, sıkıcı)\n- Terim anlam: Bilim, sanat ve spor alanlarına özel anlamlar: \"açı\", \"kök\", \"maç\" gibi.\n💡 Bir kelimenin terim anlamı, o alanda uzman olmayanın bilmeyebileceği özel anlamıdır: \"kedi sesi\"ndeki ses genel, \"dil bilgisinde ünlü ses\" terimdir.\n## Sesteş Sözcükler\nYazılışı ve okunuşu aynı, anlamı farklı sözcüklere sesteş denir: \"yüz\" (sayı), \"yüz\" (vücut bölümü), \"yüz\" (yüzmek).\n## Deyimler ve Atasözleri\n- Deyim: En az iki sözcükten oluşan, mecaz anlamlı kalıplaşmış ifade: \"Gözü gibi bakmak\", \"Burnundan solumak\".\n- Atasözü: Atalarımızın deneyimlerini anlatan öğüt veren kalıplaşmış sözler: \"Sakla samanı, gelir zamanı.\"\n✏️ Deyimlerin çoğu mecaz anlamlıdır; atasözleri ise genellikle bir yargı, ders verir.",

// 1 Cümlede Anlam
"## Öznel ve Nesnel Yargı\n- Nesnel yargı: Kişiden kişiye değişmez, herkes için aynı olan bilgi. \"Dünya, Güneş'in etrafında döner.\"\n- Öznel yargı: Kişinin duygu ve düşüncesine göre değişir. \"En güzel mevsim sonbahardır.\"\n💡 Nesnel cümleler ispatlanabilir, öznel cümleler ispatlanamaz. \"Kutup ayıları et yer.\" (nesnel) / \"Kediler çok sevimlidir.\" (öznel)\n## Neden – Sonuç (Sebep) Cümleleri\nBir olayın gerçekleşme sebebini bildiren cümlelerdir. \"Neden?\" sorusuna cevap verir.\n- \"Yağmur yağdığı için maç iptal oldu.\" (neden: yağmur / sonuç: maçın iptali)\n- Neden sözcükleri: için, çünkü, -den dolayı, -diği için.\n## Amaç – Sonuç Cümleleri\nGerçekleşme amacı bildirir; \"hangi amaçla?\" sorusuna cevap verir.\n- \"Sınavı kazanmak için çok çalıştı.\" (amaç: kazanmak)\n- Amaç sözcükleri: için, üzere, diye.\n## Koşul (Şart) Cümleleri\nBir durumun gerçekleşmesi başka bir şarta bağlıdır.\n- \"Ödevini bitirirse oyuna çıkabilir.\"\n- Koşul ekleri ve sözcükleri: -se/-sa, ise, yeter ki, ama, ancak.\n✏️ \"Sınavı kazanmak için çok çalıştı\" amaç; \"çok çalıştığı için kazandı\" neden-sonuçtur. Ayrım: sonuç mu ulaşılmak istenen hedef, yoksa gerçekleşmiş olay mı?",

// 2 Kök ve Ekler
"## Kök Nedir?\nKöy = Kelimenin anlam taşıyan, parçalanamayan çekirdeğidir.\n- \"kalemlik\" kelimesinin kökü \"kalem\"dir.\n- Kökün türü: isim kökü (kalem, ev, taş) ve fiil kökü (koş-, sev-, gül-). Fiil kökleri \"-mak\" takısı alabilir: koşmak.\n## Yapım Ekleri\nYeni kelime türeten eklerdir; kelimenin anlamını değiştirir.\n- \"göz-lük\", \"süt-çü\", \"yaz-lık\", \"sev-gi\"\n- Yapım eki alan kelimeye gövde denir.\n## Çekim Ekleri\nKelimenin anlamını değiştirmez; görevini belirler, çoğul yapar veya durum bildirir.\n- Çoğul eki: -ler/-lar (kitap-lar)\n- İyelik eki: -im, -in (kalem-im)\n- Hâl ekleri: -i, -e, -de, -den (ev-i, ev-e, ev-de, ev-den)\n- Fiil çekim ekleri: zaman ve kişi ekleri (gel-di-m)\n✏️ Kökü bulmak için ekleri ayırdıktan sonra kalan kısım anlamlı olmalıdır: \"bilgiç\" → bil- (fiil kökü) + -giç (yapım eki).",

// 3 Sıfatlar ve Zamirler
"## Sıfatlar (Ön Ad)\nİsimleri niteleyen veya belirten sözcüklerdir.\n- Niteleme sıfatı: Nasıl? sorusuna cevap verir. \"yeşil kalem\", \"uzun yol\", \"tatlı elma\"\n- Belirtme sıfatları: İşaret (bu şehir), sayı (iki kitap), belgisiz (bazı insanlar), soru (hangi kapı).\n## Zamirler (Adıl)\nİsimlerin yerini tutan sözcüklerdir.\n- Kişi zamirleri: ben, sen, o, biz, siz, onlar\n- İşaret zamirleri: bu, şu, o, bunlar\n- Belgisiz zamirler: birisi, kimse, hepsi\n- Soru zamirleri: ne, kim, hangisi\n- İyelik zamirleri (ek olarak): ev-im\n## Sıfat – Zamir Ayrımı\n- \"Bu elma çok tatlı.\" → bu, \"elma\"yı belirttiği için sıfattır.\n- \"Bu çok tatlı.\" → bu, \"elma\"nın yerine geçtiği için zamirdir.\n💡 Zamir ismin yerine geçer; sıfat ismin önünde durur ve isimle birlikte kullanılır.",

// 4 Fiiller ve Çekim
"## Fiil (Eylem) Nedir?\nHareket, oluş veya durum bildiren kelimelerdir. \"-mak / -mek\" takısını alabilir.\n- İş fiili: koşmak, yazmak, silmek (bir iş yapar, nesne alabilir)\n- Oluş fiili: büyümek, solmak, uzamak (kendiliğinden oluşur)\n- Durum fiili: uyumak, oturmak, beklemek (bir durumu bildirir)\n## Kip (Zaman) Ekleri\nFiilin hangi zamanda olduğunu gösterir.\n- Geniş zaman: -r (gel-ir)\n- Şimdiki zaman: -yor (gel-iyor)\n- Gelecek zaman: -ecek/-acak (gel-ecek)\n- Görülen (bilinen) geçmiş: -di (gel-di)\n- Duyulan (öğrenilen) geçmiş: -miş (gel-miş)\n## Kişi Ekleri\nEylemi yapan kişiyi belirtir: ben, sen, o, biz, siz, onlar.\n- gel-di-m (1. tekil: ben geldim)\n- gel-di-niz (2. çoğul: siz geldiniz)\n✏️ Fiil kökünü bulmak için \"-mak/-mek\" ekini deneriz: \"okumak\" → ok- kökü, \"yüzmek\" → yüz- kökü.",

// 5 Yazım ve Noktalama
"## \"de\" ve \"da\" Yazımı\n- Ayrı yazılır: \"bağlaç olan de/da\" → \"Sen de gel.\", \"Ali de gördü.\" (cümleden çıkarılırsa anlam bozulmaz)\n- Bitişik yazılır: \"hâl eki olan -de/-da\" → \"Evde kaldım.\", \"Okulda buluştuk.\" (cümleden çıkarılırsa anlam bozulur)\n- Bağlaç olan de/da hiçbir zaman \"te/ta\" biçiminde yazılmaz: \"Evde mi?\" → \"Sen de mi?\", \"Kitapta değil.\" → \"Kitap da değil.\"\n## \"ki\" Yazımı\n- Bağlaç olan ki ayrı yazılır: \"Gördüm ki gelmiş.\"\n- Ek olan -ki bitişik yazılır: \"sende-ki\", \"bahçe-deki\", \"yarınki\".\n- Kalıplaşmış sözcükler: belki, çünkü, sanki, mademki, oysaki bitişiktir.\n## Büyük Harflerin Kullanımı\nCümle başında, özel adlarda (Türkiye, Ayşe, Van), kurum adlarında büyük harf kullanılır.\n## Noktalama İşaretleri\n- Nokta (.): bitmiş cümle ve kısaltmalarda.\n- Virgül (,): eş görevli sözcükleri ve sıralı cümleleri ayırır.\n- Soru işareti (?): soru cümlesinin sonunda.\n- Ünlem (!): sevinç, korku, şaşkınlık bildiren cümlelerde.\n- İki nokta (:) açıklama ve listeleme öncesinde.\n✏️ \"Kitap + da\" bitişik; \"kitap da aldım\" bağlaç, ayrı. Kulağını test et: \"de\"yi çıkar, anlam bozuluyorsa ek (bitişik).",

// 6 Metin Türleri ve Okuma
"## Metin Türleri\n- Hikâye (öykü): Olay anlatır. Giriş, gelişme, sonuç bölümleri; kahramanlar ve yer-zaman vardır.\n- Bilgilendirici metin: Bilgi vermek, öğretmek için yazılır. Makale, deneme, gezi yazısı, anı gibi türler.\n- Şiir: Duyguları ölçü, uyak ve ritimle anlatır.\n- Masal, fabl, efsane: Olağanüstü olayların anlatıldığı edebi türler.\n## Hikâye Unsurları\n- Olay: Yaşanan ya da yaşanabilecek durum.\n- Kişi (kahraman): Olayın başkahramanı ve diğer karakterler.\n- Yer: Olayın geçtiği mekân.\n- Zaman: Olayın yaşandığı zaman dilimi.\n- Anlatıcı: Olayı anlatan kişi.\n## Konu, Başlık ve Ana Fikir\n- Konu: Metinde anlatılan şey (\"Kısa ve öz cevapla: Metin ne anlatıyor?\")\n- Ana fikir: Metnin vermek istediği temel mesaj, asıl düşünce.\n- Başlık: Metnin içeriğini en iyi özetleyen sözcük grubu.\n💡 Ana fikri bulmak için sor: \"Yazar, okura hangi mesajı vermek istiyor?\" Cevap çoğu zaman tek cümledir.",

// 7 Yazma ve Anlatım
"## Paragraf Nedir?\nBir düşünceyi bütünlük içinde anlatan cümle topluluğudur. Giriş, gelişme ve sonuç cümleleri vardır.\n- Giriş cümlesi: Düşünceyi tanıtır, geneldir.\n- Gelişme cümleleri: Düşünceyi örnek ve ayrıntılarla açıklar.\n- Sonuç cümlesi: Düşünceyi toparlar, özetler.\n## Anlatım Türleri\n- Açıklama: Bilgi verir, öğretir. \"Soru işareti, soru cümlelerinin sonuna konur.\"\n- Tartışma: Bir düşünceyi savunur, karşı görüşü çürütür.\n- Betimleme: Varlıkları sözcüklerle resim çizer gibi anlatır (görsel ayrıntı).\n- Öyküleme: Olayları akış içinde anlatır.\n## Düşünceyi Geliştirme Yolları\nTanımlama, örneklendirme, tanık gösterme, benzetme, karşılaştırma ve sayısal verilerden yararlanma.\n✏️ Yazarken önce plan yap: giriş → gelişme → sonuç. Sonra anlatım türünü seç, örneklerle destekle.",

// 8 Cümle Türleri
"## Yargı Sayısına Göre Cümleler\n- Basit cümle: Tek yargı (tek yüklem). \"Kardeşim her sabah erken kalkar.\"\n- Sıralı cümle: Birden çok bağımsız yargı virgül veya noktalı virgülle sıralanır. \"Geldi, oturdu, anlattı.\"\n- Birleşik cümle: Tek ana yargı + onu tamamlayan yan yargı(lar). \"Sınava girmeden önce kısa bir özet yaptım.\"\n💡 Yüklem sayısına bak: tek yüklem varsa basit, birden çok yüklem varsa sıralı ya da birleşik.\n## Yüklemin Yerine ve Anlamına Göre\n- Kurallı cümle: Yüklem sonda. \"Yağmur dinmeden yola çıktık.\"\n- Devrik cümle: Yüklem sonda değildir. \"Çıktık yola yağmur dinmeden.\"\n- Olumlu / olumsuz / soru cümleleri de anlamlarına göre gruplandırılır.\n✏️ \"Yağmur yağınca ıslandık.\" → \"yağınca\" yan yargı, \"ıslandık\" ana yargı: birleşik cümle.",

// 9 Anlatım Bozuklukları
"## Gereksiz Sözcük Kullanımı\nAnlamı zaten başka bir sözcükte olan sözcükler cümleye eklenirse bozukluk olur.\n- Yanlış: \"Dışarıda kar yağmaktadır.\" → \"Kar\" zaten \"yağar\"; \"Dışarıda kar yağıyor.\" olmalı.\n- Yanlış: \"Bütün hepsi geldi.\" → \"Bütün\" ve \"hepsi\" aynı anlamda.\n## Anlamdaş / Yakın Anlamlı Sözcüklerin Bir Arada Kullanımı\n\"Zaten o da aynı şekilde bu duruma karşı çıktı.\" → \"zaten\", \"aynı şekilde\" gereksizdir.\n## Yanlış Anlamda Sözcük\nKelimenin cümleye uymayan anlamda kullanılması: \"Televizyonun sesini yükseltti.\" değil \"sesini açtı\" (anlam bağlamına dikkat).\n## Mantık ve Yapı Hataları\n- Çelişki: \"Kesinlikle belki gelir.\" → \"kesinlikle\" ile \"belki\" çelişir.\n- Deyimin yanlış kullanımı: \"Eli açık davrandı\" yerine \"cömert davrandı\" gibi anlam karışıklığı.\n💡 Bozukluğu bulmak için cümleyi yavaşça oku; anlamsız tekrar, çelişki ya da eksik öge ara.",

// 0 - placeholder (yok)
],

/* ===================== MATEMATİK ===================== */
mat6: [
// 0 Doğal Sayılarla İşlemler
"## Üslü İfadeler\nBir sayının kendisiyle tekrar tekrar çarpılmasını kısa gösterimi: taban × üs.\n- 2³ = 2 × 2 × 2 = 8 (taban 2, üs 3)\n- 5² = 5 × 5 = 25\n- 10⁶ = 1 000 000 (10'un kuvvetleri kolay: 1'in yanına üs kadar 0)\n💡 1'in her kuvveti 1'dir; taban 10 ise üs, sıfır sayısını verir.\n## İşlem Önceliği\nSırayla: 1) Parantez içleri 2) Üslü ifadeler 3) Çarpma ve bölme 4) Toplama ve çıkarma.\n- 2 + 3 × 4 = 2 + 12 = 14 (önce çarpma!)\n- (2 + 3) × 4 = 5 × 4 = 20\n- 2 + 3 × 4 ÷ 2 = 2 + 12 ÷ 2 = 2 + 6 = 8\n## Dağılma Özelliği ve Ortak Çarpan\n- a × (b + c) = a × b + a × c\n- 6 × 8 + 6 × 2 = 6 × (8 + 2) = 6 × 10 = 60\n✏️ Çarpma işlemi toplama üzerine dağılır; ortak çarpan parantezine almak işlemi hızlandırır.",

// 1 Çarpanlar ve Katlar
"## Çarpan (Bölen)\nBir doğal sayıyı kalansız bölen sayılar, o sayının çarpanlarıdır.\n- 12'nin çarpanları: 1, 2, 3, 4, 6, 12 (1×12, 2×6, 3×4)\n- Çarpanlar sayıyı tam böler; en küçük çarpan 1, en büyük çarpan sayının kendisidir.\n## Katlar\nBir sayının katları, sayıyla doğal sayıların çarpımıdır.\n- 5'in katları: 5, 10, 15, 20, 25...\n- Ortak kat: İki sayının katlarında aynı olan değerler (12 ve 18'in ortak katı 36, 72...).\n## Asal Sayılar\n1 ve kendisinden başka çarpanı olmayan 1'den büyük sayılar: 2, 3, 5, 7, 11, 13, 17, 19...\n💡 2, çift olan tek asal sayıdır. 1 asal değildir.\n## Bölünebilme Kuralları\n- 2: son rakam çift (0,2,4,6,8)\n- 3: rakamlar toplamı 3'ün katı\n- 4: son iki rakam 4'ün katı\n- 5: son rakam 0 veya 5\n- 9: rakamlar toplamı 9'un katı\n- 10: son rakam 0\n✏️ Bir sayıya tam bölünme için kuralları tek tek dene; asal çarpanlara ayırmada en küçük asaldan başla.",

// 2 Kümeler
"## Küme Nedir?\nİyi tanımlanmış, ortak özellikli nesnelerin (elemanların) topluluğudur.\n- \"Haftanın günleri\", \"1'den 5'e kadar olan sayılar\" kümedir.\n- \"Uzun boylu öğrenciler\" küme değildir (uzunluk kişiye göre değişir).\n## Gösterimler\n- Liste yöntemi: A = {1, 2, 3}\n- Ortak özellik yöntemi: A = {0, 1, 2, 3} → \"4'ten küçük doğal sayılar\"\n- Venn şeması: Elemanlar kapalı bir eğri (genelde daire) içine yazılır.\n## Eleman Kavramı\nEleman kümenin içindeki her bir nesnedir.\n- ∈ : elemanıdır (3 ∈ A)\n- ∉ : elemanı değildir (5 ∉ A)\n- Eleman sayısı s(A) veya n(A) ile gösterilir.\n## Özel Kümeler\n- Boş küme (∅ veya {}): hiç elemanı olmayan küme. s(∅) = 0\n- Evrensel küme: üzerinde çalışılan bütün elemanları içerir.\n- Eşit kümeler: elemanları aynı olan kümeler (sıra önemli değil).\n✏️ \"Sınıfımızdaki\" ifadeleri her zaman küme değildir; özellik iyi tanımlı olmalıdır.",

// 3 Tam Sayılar
"## Tam Sayılar\nNegatif tam sayılar, 0 ve pozitif tam sayıların tümü: ..., -3, -2, -1, 0, 1, 2, 3, ...\n- Pozitif: 0'dan büyük (+)\n- Negatif: 0'dan küçük (−)\n- 0, ne pozitif ne negatiftir; doğal sayıdır.\n## Sayı Doğrusu\nSağa doğru büyür, sola doğru küçülür. Negatifler 0'ın solunda, pozitifler sağındadır.\n- Sıralama: −3 < −1 < 0 < 2 < 5\n## Mutlak Değer\nSayının 0'a olan uzaklığıdır; her zaman pozitif ya da 0'dır.\n- |−7| = 7, |7| = 7, |0| = 0\n💡 Mutlak değer işaretinin içi negatif olsa da sonuç pozitiftir.\n## Tam Sayılarla İşlemler\n- Aynı işaretlileri topla, işareti koy: (−5) + (−3) = −8\n- Zıt işaretlilerde büyükten küçüğü çıkar, büyüğün işaretini koy: (−5) + 3 = −2\n- Çıkarma: işareti değiştirip topla: (−5) − (−3) = (−5) + 3 = −2\n- Çarpma/bölme: aynı işaret → pozitif, zıt işaret → negatif: (−2) × (−3) = 6, (−6) ÷ 2 = −3\n✏️ İki negatif sayının çarpımı pozitiftir; tek negatif varsa sonuç negatiftir.",

// 4 Kesirlerle İşlemler
"## Kesir Nedir?\nBir bütünün eş parçalarından kaç tanesini aldığımızı gösterir: pay / payda.\n- 3/4: bütün 4 eş parçaya bölünmüş, 3 parçası alınmış.\n- Payda 0 olamaz.\n## Toplama ve Çıkarma\nPaydalar eşitse paylar toplanır/çıkarılır, payda aynı kalır.\n- 2/5 + 1/5 = 3/5\nPaydalar farklıysa önce genişletilerek paydalar eşitlenir.\n- 1/2 + 1/4 = 2/4 + 1/4 = 3/4\n## Çarpma\nPaylar çarpılır, paydalar çarpılır.\n- 2/3 × 3/4 = 6/12 = 1/2 (sadeleştirme!)\n## Bölme\nİlk kesir aynı kalır, ikinci kesir ters çevrilir ve çarpılır.\n- 3/4 ÷ 2/5 = 3/4 × 5/2 = 15/8\n## Tam Sayılı Kesir\nTam kısımlı kesirdir: 1 1/2 = 3/2 (tam × payda + pay).\n💡 Çarpma öncesi sadeleştirme işlemi kolaylaştırır.",

// 5 Ondalık Gösterim
"## Ondalık Gösterim\nVirgülle ayrılmış kesir gösterimidir. Virgülün sağı ondalık kısım, solu tam kısımdır.\n- 3,25 → 3 tam, 25 yüzde birlik.\n## Kesir ↔ Ondalık Dönüşüm\n- 1/2 = 0,5 ; 3/4 = 0,75 ; 1/5 = 0,2\n- Paydayı 10, 100, 1000'e genişletmek kolay yol: 3/4 → 75/100 → 0,75\n## Toplama ve Çıkarma\nVirgüller alt alta getirilir; eksik basamaklara 0 eklenir.\n- 3,2 + 1,45 = 3,20 + 1,45 = 4,65\n## Çarpma\nNormal çarpılır, sonra virgülle ayrılan toplam basamak sayısı kadar sağdan virgül kaydırılır.\n- 2,5 × 1,2 = 3,00 → 3\n- 10, 100, 1000 ile çarpım: virgül sağa kayar. 4,56 × 10 = 45,6\n## Bölme\n- 10, 100, 1000 ile bölümde virgül sola kayar: 45,6 ÷ 10 = 4,56\n- Ondalıklı bölen varsa virgüllerden kurtuluruz: 1,5 ÷ 0,5 = 15 ÷ 5 = 3\n## Yuvarlama\nİstenen basamağa bak: sağdaki rakam 5 ve üzeriyse yukarı yuvarla.\n- 4,56 ondalıkları yuvarla → 4,6 ; 4,54 → 4,5\n✏️ Ondalık sıralarken önce tam kısma, eşitse ondalık basamaklara sırayla bak.",

// 6 Oran
"## Oran Nedir?\nİki çokluğun kesir biçiminde karşılaştırılmasıdır. a/b veya a:b şeklinde gösterilir.\n- Sınıfta 12 kız, 18 erkek varsa kız/erkek oranı = 12/18 = 2/3\n## Birimli Oran\nBirimleri farklıdır (km/sa, TL/kg): \"aracın hızı 80 km/sa\".\n## Birimsiz Oran\nAynı tür çoklukların oranıdır, birimi yoktur: \"kız sayısı / erkek sayısı\".\n## Eşit Oranlar (Oran Orantı)\nOranlar sadeleştirilip genişletilerek eşitlenebilir.\n- 1/2 = 2/4 = 3/6 ... eşit oranlardır.\n💡 Oran çoklukların sırasına dikkat et: \"a'nın b'ye oranı\" yazıldığı sırayla kurulur.",

// 7 Cebirsel İfadeler
"## Değişken, Terim ve Katsayı\n- Değişken (bilinmeyen): Değeri bilinmeyen, harfle gösterilen sayı: x, y, a.\n- Terim: Toplama/çıkarmayla ayrılan her parça: 2x + 5 → iki terim (2x ve 5).\n- Katsayı: Terimin sayı kısmı: 2x'te katsayı 2, x'te 1'dir.\n- Sabit terim: Değişkeni olmayan terim: 2x + 5'te 5.\n## Benzer Terimler\nDeğişkeni aynı olan terimlerdir; birleştirilir.\n- 3x + 2x = 5x\n- 4a − a = 3a\n- x² ile x benzer değildir.\n## İfadenin Değeri\nDeğişkene değer vererek hesaplanır: 2x + 5, x = 3 için → 2·3 + 5 = 11.\n✏️ Katsayısı yazılmayan x'in katsayısı 1'dir; −x'in katsayısı −1'dir.",

// 8 Veri Analizi
"## Aritmetik Ortalama\nTüm değerler toplanır, değer sayısına bölünür.\n- Veriler: 4, 6, 8 → ortalama = (4+6+8) ÷ 3 = 18 ÷ 3 = 6\n## Mod (Tepe Değer)\nEn çok tekrar eden değerdir.\n- Veriler: 3, 3, 5, 7, 7, 7 → mod = 7\n- Tüm değerler farklıysa mod yoktur; iki değer aynı sıklıktaysa çift mod olabilir.\n## Medyan (Ortanca)\nVeriler küçükten büyüğe sıralanır; ortadaki değerdir.\n- Tek sayıda veri: ortanca tam ortadaki: 3, 5, 8 → medyan 5\n- Çift sayıda veri: ortadaki iki değerin ortalaması: 3, 5, 8, 10 → (5+8)÷2 = 6,5\n## Açıklık\nEn büyük değer ile en küçük değer arasındaki farktır.\n- Veriler: 2, 5, 9 → açıklık = 9 − 2 = 7\n💡 Önce verileri sırala; medyan ve açıklık için bu şarttır.",

// 9 Açılar
"## Açı Nedir?\nBir noktadan (köşe) çıkan iki ışının oluşturduğu şekildir. Birimi derecedir (°).\n## Açı Türleri\n- Dar açı: 0° < a < 90°\n- Dik açı: 90°\n- Geniş açı: 90° < a < 180°\n- Doğru açı: 180°\n- Tam açı: 360°\n## Komşu Açılar\nKöşeleri ve birer kolları ortak olan, iç bölgeleri ortak olmayan açılardır.\n## Tümler Açılar\nÖlçüleri toplamı 90° olan iki açıdır.\n- 30° ile 60° tümlerdir. Birinin ölçüsü 90° − diğeri.\n## Bütünler Açılar\nÖlçüleri toplamı 180° olan iki açıdır.\n- 30° ile 150° bütünlerdir. Birinin ölçüsü 180° − diğeri.\n✏️ Tümler = 90 (T harfinde 1 dik açı), Bütünler = 180 (B harfinde 1 doğru gibi dümdüz).",

// 10 Alan Ölçme
"## Alan Nedir?\nBir yüzeyin kapladığı bölgedir. Birim kare cinsinden ölçülür (cm², m²).\n## Paralelkenarın Alanı\nAlan = Taban × Yükseklik (A = a × h).\n- Tabanı 8 cm, yüksekliği 5 cm olan paralelkenarın alanı = 8 × 5 = 40 cm²\n💡 Paralelkenarda yükseklik, tabana dik inen uzaklıktır; kenar değil!\n## Üçgenin Alanı\nAlan = Taban × Yükseklik ÷ 2 (A = a × h ÷ 2).\n- Tabanı 10 cm, yüksekliği 6 cm olan üçgenin alanı = 10 × 6 ÷ 2 = 30 cm²\n- Dik üçgende taban ve yükseklik dik kenarlardır.\n## Alan Birimleri\n1 m² = 100 dm² = 10 000 cm². Dönüşümde 100 ile çarpılır/bölünür.\n✏️ Üçgenin alanını bulurken 2'ye bölmeyi unutma! Paralelkenar, iki eş üçgenden oluşur.",

// 11 Çember
"## Çember ve Daire\n- Çember: Merkezden eşit uzaklıktaki noktaların oluşturduğu kapalı eğridir (içi boş).\n- Daire: Çemberin sınırladığı bölgenin tamamı (içi dolu).\n## Yarıçap ve Çap\n- Yarıçap (r): merkezden çembere çizilen doğru parçası.\n- Çap (R): çemberin bir noktasından merkezden geçerek karşı noktaya uzanan doğru parçası. Çap = 2 × yarıçap.\n## Çevre Hesaplama\nÇevre = 2 × π × r veya π × çap.\n- π (pi) yaklaşık 3,14'tür (5. sınıfta ≈ 3 kullanılır).\n- r = 5 cm ise çevre ≈ 2 × 3 × 5 = 30 cm\n## Çember Çizme\nPergel: Ucu merkeze konur, kalem kısmı yarıçap kadar açılarak çizilir.\n✏️ Yarıçap verilirse çapı bulmak için 2 ile çarp; çap verilirse yarıçapı bulmak için 2'ye böl.",

// 12 Geometrik Cisimler
"## Dik Prizmalar\nTabanları birbirine paralel ve eş çokgenler; yan yüzleri dikdörtgen olan cisimlerdir.\n- Kare prizma, dikdörtgenler prizması, üçgen prizma, beşgen prizma...\n## Yüz, Ayrıt, Köşe\n- Yüz: Prizmayı sınırlayan yüzeyler.\n- Ayrıt: İki yüzün kesiştiği doğru parçası.\n- Köşe: Ayrıtların kesiştiği nokta.\n- Dikdörtgenler prizması: 6 yüz, 12 ayrıt, 8 köşe.\n- Kare prizma: 6 yüz, 12 ayrıt, 8 köşe (2 kare + 4 dikdörtgen yüz).\n- Üçgen prizma: 5 yüz, 9 ayrıt, 6 köşe.\n## Yüzey Açınımı\nPrizmanın açılımı, tüm yüzlerin aynı düzlemde çizilmiş halidir.\n## Hacim Kavramı\nPrizmanın içini kaç birim küp doldurur: hacim = taban alanı × yükseklik.\n💡 Dikdörtgenler prizması için hacim = a × b × c (uzunluk × genişlik × yükseklik).",

// 13 Sıvı Ölçme
"## Sıvı Ölçme Birimleri\n- Temel birim: litre (L).\n- Alt birim: mililitre (mL).\n- 1 L = 1000 mL\n- 0,5 L = 500 mL\n## Birim Çevirme\nLitre → mililitre: 1000 ile çarp. Mililitre → litre: 1000'e böl.\n- 2,5 L = 2500 mL\n- 750 mL = 0,75 L\n## Sıvı – Hacim İlişkisi\n1 L su, 1000 cm³ hacim kaplar. Bu yüzden sıvı ölçüleri hacimle ilişkilendirilir.\n- 1 L = 1 dm³\n## Sıvı Problemleri\nKaplara bölüştürme, karışım ve doldurma problemlerinde mL/L dönüşümüne dikkat edilir.\n✏️ \"1 L suyu 4 eş bardağa eşit paylaştır\" → her bardak 1000 ÷ 4 = 250 mL.",

// 14 Hacim Ölçme
"## Birim Küp\nKenarı 1 birim olan küptür; hacim ölçmede temel birimdir.\n## Dikdörtgenler Prizmasının Hacmi\nHacim = Taban alanı × Yükseklik = a × b × c.\n- 2 × 3 × 4 boyutlarındaki prizma 24 birim küp alır.\n## Hacim Birimleri\n- cm³, m³, dm³.\n- 1 m³ = 1 000 000 cm³\n- 1 dm³ = 1 L (sıvı ile ilişki!)\n## Hacim Problemleri\nPrizma hacmi bulunup bölüştürme, doldurma ve taşırma problemleri çözülür.\n✏️ Hacim hesaplarken üç boyutu da çarp; uzunluk, genişlik ve yüksekliği aynı birimde kullan.",

// 15 Veri Toplama ve Değerlendirme
"## Araştırma Sorusu\nCevabı kişiden kişiye değişen, birden çok cevaplı sorudur: \"Sınıfın en sevdiği meyve hangisidir?\"\n💡 \"Herkesin boyu kaç cm?\" araştırma sorusu; \"Ali'nin boyu kaç?\" araştırma sorusu değildir (tek cevap).\n## Veri Toplama\nAnket, ölçüm ve gözlemle veriler toplanır; düzenlenir.\n## Tablolar\n- Sıklık tablosu: veri değerlerini ve kaç kez tekrar ettiğini gösterir.\n- Sütun ve çizgi grafikleri: veriyi görselleştirir.\n## Grafik Yorumlama\nGrafikten en çok/en az, toplam, fark ve oran çıkarımları yapılır.\n✏️ Veri toplamadan önce araştırma sorusunu net yaz; soruya uygun olmayan verileri eler."
],

/* ===================== FEN BİLİMLERİ ===================== */
fen6: [
// 0 Güneş Sistemi ve Tutulmalar
"## Güneş Sistemi\nGüneş'in etrafında dolanan 8 gezegen ve gök cisimlerinin tamamıdır.\nGüneş'e yakınlık sırası: Merkür, Venüs, Dünya, Mars, Jüpiter, Satürn, Uranüs, Neptün.\n- İç gezegenler: Merkür, Venüs, Dünya, Mars (kayalık)\n- Dış gezegenler: Jüpiter, Satürn, Uranüs, Neptün (gaz devleri)\n💡 Hatırlatma: \"Mavi Vapur Durmadan Mars'a Jüpiter'i Söylerdi Uranüs Neptün\" → sıra ezberlenir.\n## Gök Taşları ve Kuyruklu Yıldızlar\n- Meteor (gök taşı): uzaydan atmosfere giren kaya parçası; Dünya'ya ulaşanına gök taşı denir.\n- Kuyruklu yıldız: Güneş'e yaklaştıkça kuyruğu oluşan buzlu gök cismi.\n## Güneş Tutulması\nAy, Güneş ile Dünya arasına girer; Ay'ın gölgesi Dünya'ya düşer. Gündüz yaşanır.\n## Ay Tutulması\nDünya, Güneş ile Ay arasına girer; Ay'ın üzerine Dünya'nın gölgesi düşer. Gece yaşanır.\n✏️ Güneş tutulması yeni ay evresinde, Ay tutulması dolunay evresinde gerçekleşir.",

// 1 Vücudumuzdaki Sistemler
"## Destek ve Hareket Sistemi\nVücuda şekil verir, organları korur ve hareketi sağlar.\n- İskelet: kemiklerden oluşur. Kafatası, omurga, göğüs kafesi, kol-bacak kemikleri.\n- Eklem: kemiklerin birleştiği yerler (oynar, yarı oynar, oynamaz).\n- Kaslar: iskeletle birlikte hareketi sağlar (düz kas, çizgili kas, kalp kası).\n## Dolaşım Sistemi\nKanı vücuda pompalar; besin ve oksijeni taşır.\n- Kalp: kanı pompalayan organ.\n- Kan damarları: atardamar (kalpten), toplardamar (kalbe), kılcal damar.\n- Kan: alyuvar, akyuvar, kan pulcukları ve plazmadan oluşur.\n💡 Kalp kası, çizgili kastır ama istemsiz çalışır; ömrümüz boyunca durmadan atar.",

// 2 Kuvvet ve Hareket
"## Kuvvet Nedir?\nBir cisme etki eden, onu hareket ettirebilen, durdurabilen ya da şeklini değiştirebilen etkidir.\n- Kuvvet bir vektördür: büyüklüğü ve yönü vardır. Birimi Newton (N), dinamometreyle ölçülür.\n## Bileşke Kuvvet\nAynı yöndeki kuvvetler toplanır, zıt yöndekiler çıkarılır.\n- Aynı yönde: F₁ + F₂ (hareketi hızlandırır)\n- Zıt yönde: |F₁ − F₂| (büyük olan yönde)\n## Dengelenmiş ve Dengelenmemiş Kuvvet\n- Dengelenmiş: bileşke kuvvet 0'dır; cisim duruyorsa durur, sabit hızla gidiyorsa devam eder.\n- Dengelenmemiş: bileşke 0 değildir; cisim hızlanır ya da yavaşlar.\n## Sürtünme Kuvveti\nHarekete karşı koyan, cisimle yüzey arasındaki kuvvettir.\n- Cismi yavaşlatır, pürüzlü yüzeylerde daha büyüktür.\n- Hava ve su direnci de bir tür sürtünmedir (paraşüt, balık şekli).\n✏️ Bileşke kuvvet sıfır değilse cisim mutlaka hızlanır ya da yavaşlar — yön değiştirebilir.",

// 3 Madde ve Isı
"## Maddelerin Tanecikli Yapısı\nBütün maddeler gözle görülemeyen, boşluklu, hareketli taneciklerden oluşur.\n- Tanecikler arası boşluk: gaz > sıvı > katı\n- Tanecik hareketliliği de aynı sırayla fazladır.\n## Isı ve Sıcaklık\n- Isı: sıcaklıkları farklı maddeler arasında aktarılan enerjidir (kalori veya joule ile ölçülür).\n- Sıcaklık: bir maddenin taneciklerinin ortalama hareket enerjisinin göstergesidir (°C termometreyle).\n💡 Isı bir enerji çeşididir, maddeyi oluşturmaz; sıcaklık ise ölçümdür.\n## Isı Alışverişi\nSıcak maddeden soğuk maddeye doğru olur; dengeye ulaşınca sona erer.\n## Genleşme ve Büzülme\n- Genleşme: ısınan maddenin hacminin artması (kavanoz kapağı sıcak suda açılır).\n- Büzülme: soğuyan maddenin hacminin azalması.\n- Katı-sıvı genel olarak genleşir; su 4°C'den soğurken büzülür (buz suda yüzer).",
// 4 Ses ve Özellikleri
"## Ses Nasıl Oluşur?\nSes, maddelerin titreşmesiyle oluşur. Titreşen kaynak, çevresindeki tanecikleri titreştirerek sesi yayar.\n- Ses kaynağı titreşmezse ses oluşmaz.\n## Sesin Yayılması\nSes, katı, sıvı ve gaz ortamlarda yayılır; boşlukta yayılamaz!\n- Hız: katı > sıvı > gaz (tanecikler ne kadar yakınsa o kadar hızlı).\n- Yüksek ve alçak yerlerde yankı, sesin yansımasıdır.\n## Frekans (Yükseklik)\nSesin ince-kalınlığıdır. Yüksek frekans → ince ses, düşük frekans → kalın ses.\n- Sesin yüksekliği kaynağın titreşim sayısına bağlıdır.\n## Genlik (Gürlük)\nSesin şiddetidir; ses kaynağının titreşim genliğine bağlıdır.\n- Büyük genlik → gür (yüksek) ses, küçük genlik → kısık ses.\n- Genliği enerjiye, frekansı yüksekliğe bağla.\n✏️ Gürlük \"ses şiddeti\"dir (kaç dB), yükseklik \"ince-kalın\"dır — karıştırma.",

// 5 Vücudumuzdaki Sistemler ve Sağlığı
"## Solunum Sistemi\nOksijeni alıp karbondioksiti dışarı verir.\n- Burun, yutak, gırtlak, soluk borusu, akciğerler.\n- Alveoller (hava kesecikleri) gaz alışverişinin yapıldığı yerdir.\n## Boşaltım Sistemi\nKanı süzer, atık maddeleri (üre, fazla su) vücuttan uzaklaştırır.\n- Böbrekler (idrar üretimi), idrar borusu (üreter), idrar kesesi, idrar kanalı.\n- Deri ve akciğerler de boşaltıma yardımcı olur (ter, su buharı).\n## Denetleyici ve Düzenleyici Sistem\nSinirler ve iç salgı bezleri vücudun düzenini sağlar.\n- İç salgı bezleri hormon salgılar: büyüme, şeker düzenleme (pankreas) gibi görevler.\n## Sistemlerin Sağlığı\nDengeli beslenme, düzenli uyku, temizlik ve spor; sigaradan uzak durmak akciğer ve kalbi korur.\n💡 Böbrekler \"vücudun süzgeci\", kalp \"vücudun pompası\"dır; soluk borusu ile yemek borusunu karıştırma (gırtlak üstte).",

// 6 Elektrik İletkenliği
"## İletken ve Yalıtkan Maddeler\n- İletkenler: elektriği ileten maddeler (metaller: bakır, demir, altın; tuzlu su).\n- Yalıtkanlar: elektriği iletmeyen maddeler (plastik, ahşap, cam, kauçuk, saf su).\n## Devre Elemanları\nPil (enerji kaynağı), ampul (alıcı), anahtar (açıp kapama), bağlantı kabloları.\n- Devre kapalıysa ampul yanar.\n## Elektriksel İletkenlik Deneyi\nTest edilen madde devreye bağlanır; ampul yanıyorsa madde iletkendir.\n## Güvenlik Önlemleri\n- Islak elle elektrik düğmelerine dokunma (su iletkendir).\n- Yalıtkan eldiven ve kablolar kullanılır.\n- Prizlere metal cisim sokma; pili kısa devre yapma.\n💡 Saf su yalıtkandır ama tuzlu su iletkendir; ıslak eller iletkenliği artırır, tehlikeye yol açar."
],

/* ===================== SOSYAL BİLGİLER ===================== */
sos6: [
// 0 Biz ve Değerlerimiz
"## Sosyal Roller\nBireyin toplum içinde üstlendiği görev ve davranış kalıplarına sosyal rol denir.\n- Bir kişi aynı anda birden çok role sahiptir: öğrenci, evlat, kardeş, arkadaş.\n- Her rolün gerektirdiği sorumluluklar vardır.\n## Değerlerimiz\nBirlikte yaşamayı kolaylaştıran davranış ilkeleridir.\n- Yardımlaşma, dürüstlük, sorumluluk, hoşgörü, saygı, adalet.\n## Empati\nKendimizi karşımızdakinin yerine koyup onun duygularını anlamaya çalışmaktır.\n💡 \"Kendine yapılmasını istemediğini başkasına yapma\" en temel hoşgörü kuralıdır.\n## Sorumluluklarımız\nÖdevlerimizi yapmak, sözümüzde durmak, kurallara uymak hem bireysel hem toplumsal barışı güçlendirir.",

// 1 Kültür ve Miras
"## Orhun Yazıtları\nTürklerin bilinen ilk alfabeli yazılı eserleridir (8. yüzyıl).\n- Orhun Nehri çevresinde dikilmiştir (bugün Moğolistan).\n- Göktürk alfabesiyle yazılmış; Türk adının geçtiği ilk metinlerdir.\n- Kitabeler: Bilge Kağan, Kültigin, Tonyukuk.\n## İlk Türk Devletleri\nGöktürkler, Hunlar, Uygurlar... Devlet yönetimi, kağan, toy (kurultay) gibi kavramlar.\n## Anadolu Medeniyetleri\nHititler, Frigler, Urartular, Lidyalılar, İyonlar gibi uygarlıkların mirası.\n## Kültürel Miras\nTarihi yapılar, el sanatları, yemekler, türküler ve gelenekler kültürümüzü oluşturur.\n✏️ Yazının olmadığı dönemde tarih yazılı değil sözlü ve arkeolojik bulgularla öğrenilir; Orhun Yazıtları bu yüzden değerlidir.",

// 2 İnsanlar, Yerler ve Çevreler
"## Türkiye'nin Konumu\nTürkiye, Asya ile Avrupa'yı birbirine bağlayan köprü konumundadır.\n- Üç tarafı denizlerle çevrilidir; komşuları ve denizleriyle stratejik önem taşır.\n## Yeryüzü Şekilleri\nDağ, ova, plato, akarsu, göl gibi şekiller Türkiye'nin yüzeyini oluşturur.\n- Kuzey: Kuzey Anadolu Dağları; Güney: Toros Dağları.\n## Harita Okuma\nÖlçek, yön oku, lejant (işaretler anahtarı) ve renkler (mavi su, yeşil alçak, kahverengi yüksek).\n## İklim ve Yaşam\n- Karadeniz: bol yağışlı, yeşil.\n- Akdeniz: sıcak ve kurak yazlar.\n- İç Anadolu: karasal iklim (yaz sıcak, kış soğuk).\n💡 İklim, insanların giyimini, tarım ürünlerini, konut tipini ve yaşam biçimini doğrudan etkiler.",

// 3 Türk Tarihinde Yolculuk
"## Göçler\nTürkler, tarih boyunca Orta Asya'dan dünyanın farklı bölgelerine göç etmiştir.\n- Göç nedenleri: kuraklık, nüfus artışı, otlakların yetmemesi, savaşlar.\n- Göçlerle Türk kültürü geniş bir alana yayılmıştır.\n## İlk Türk Devletleri\nHunlar, Göktürkler, Uygurlar, Karahanlılar...\n- Kurultay (toy): devlet işlerinin görüşüldüğü meclis.\n- Kağan: devleti yöneten hükümdar; töre: yazısız hukuk kuralları.\n## İpek Yolu ve Baharat Yolu\nDoğu ile Batı arasında ticaret ve kültür alışverişini sağlayan yollardır.\n- İpek, kâğıt, baharat, din ve bilgi bu yollarla yayılmıştır.\n- Yollar üzerindeki devletler ticaretten büyük kazanç sağlamıştır.\n✏️ İpek Yolu yalnızca ticaret değil; bilgi, din ve kültür etkileşiminin de köprüsüdür.",

// 4 Yönetime Katılıyorum
"## Yönetim Biçimleri\n- Cumhuriyet: halkın seçtiği temsilciler yönetir; güç halktandır.\n- Monarşi: yönetimin tek kişide (kral, padişah) olduğu sistem.\n- Oligarşi: küçük bir grubun yönettiği sistem.\n## Parlamento ve Seçimler\n- TBMM (Türkiye Büyük Millet Meclisi): yasaları yapar.\n- Milletvekilleri, halkın oylarıyla belirli süre için seçilir.\n- Seçme ve seçilme hakkı, demokratik katılımın temelidir.\n## Demokrasinin İlkeleri\nEşitlik, özgürlük, adalet, halkın kendini yönetmesi.\n## Katılım Yolları\nOy kullanmak, sivil toplum kuruluşlarında çalışmak, dilekçe hakkı, meclis kararlarını izlemek.\n💡 Demokraside sadece seçmek değil; seçilmek, izlemek ve söz hakkı kullanmak da katılımdır.",

// 5 Bilim ve Teknolojinin Gelişimi
"## Önemli Buluşlar ve Etkileri\n- Yazının bulunuşu: bilgi birikiminin aktarılmasını sağladı.\n- Tekerlek: ulaşımı ve ticareti kolaylaştırdı.\n- Pusula: yön bulmayı sağladı, coğrafi keşifleri kolaylaştırdı.\n- Matbaa: bilginin hızlı ve ucuz yayılmasını sağladı.\n## Bilim ve Teknoloji İlişkisi\nBilim yeni bilgiler üretir; teknoloji bu bilgiyi hayatımıza uyarlar. İkisi birbirini besler.\n## Buluşların Topluma Etkileri\nBuluşlar üretimi artırır, işleri kolaylaştırır, yaşam kalitesini yükseltir; ama bilinçsiz kullanım (aşırı ekran, çevre kirliliği) sorun yaratabilir.\n✏️ Bir buluşun önemini sor: \"Bundan önce nasıl yapılıyordu? Bu buluş neyi değiştirdi?\"",

// 6 Küresel Bağlantı
"## Küresel Etkileşim\nDünyadaki ülkelerin siyasi, ekonomik ve kültürel olarak birbirine bağlanmasıdır.\n- Dünya, \"küresel bir köy\" gibi herkesin birbiriyle iletişim halinde olduğu bir yer olmuştur.\n## Ticaret\nÜlkeler ihtiyaçlarını dışarıdan alır, fazlasını dışarıya satar (ithalat-ihracat).\n- Türkiye'den ihraç edilenler: otomotiv, tekstil, tarım ürünleri.\n## Uluslararası İş Birliği\nBirleşmiş Milletler, NATO, Avrupa Birliği gibi kuruluşlar ülkeler arasında iş birliğini sağlar.\n## Küresel Sorunlar\nİklim değişikliği, açlık, savaş ve göç tüm dünyayı ilgilendirir; ortak çözüm gerekir.\n💡 Küresel sorunlar tek bir ülkenin çabasıyla çözülemez; dayanışma şarttır.",

// 7 Üretim, Dağıtım ve Tüketim
"## Üretim\nHam maddelerin emek ve sermaye ile tüketilebilir mala dönüştürülmesidir.\n- Örnek: buğday → un → ekmek\n## Dağıtım\nÜretilen malların tüketiciye ulaştırılmasıdır (depolama, taşıma, mağazalar).\n## Tüketim\nÜretilen malların ihtiyaçları karşılamak üzere kullanılmasıdır.\n## Bilinçli Tüketim ve Tasarruf\n- İhtiyaç ile isteği ayırt etmek.\n- Alışverişte etiket, TSE damgası, son kullanma tarihine bakmak.\n- Tasarruf: kaynakları ve parayı gerektiği kadar kullanmak.\n✏️ \"Okul çantası\" ihtiyaç, \"pahalı oyuncak\" istektir; bilinçli tüketici önce ihtiyacını alır."
],

/* ===================== İNGİLİZCE ===================== */
ing6: [
// 0 Life – Hayat
"## Simple Present (Geniş Zaman)\nAlışkanlıklar ve günlük rutinler için kullanılır.\n- I get up at seven o'clock. (Saat yedide kalkarım.)\n- He/She/It ile fiile -s eklenir: She watches TV in the evening.\n- Olumsuz: I don't like / He doesn't like.\n- Soru: Do you play football? / Does he play football?\n## Günlük Aktiviteler\nget up, brush my teeth, have breakfast, go to school, do homework, go to bed.\n## Saatler\n- 7:00 → It's seven o'clock.\n- 7:15 → It's quarter past seven.\n- 7:30 → It's half past seven.\n- 7:45 → It's quarter to eight.\n💡 Saatlerde \"past\" geçiyor (past seven), \"to\" kala (to eight) anlamına gelir.",

// 1 Yummy Breakfast – Kahvaltı
"## Yiyecek ve İçecekler\nbread, cheese, eggs, milk, juice, tea, honey, butter, olives, jam.\n- \"I have toast and tea for breakfast.\"\n## Some / Any\n- Olumlu: some → I want some cheese.\n- Olumsuz ve soru: any → I don't want any milk. / Do you have any eggs?\n## There is / There are\n- There is + tekil: There is an apple on the table.\n- There are + çoğul: There are two eggs in the fridge.\n## İstek Cümleleri\n- I would like some tea, please.\n- Can I have some juice? / I want some honey.\n✏️ Tekil için \"is\", çoğul için \"are\"; \"some\" olumlu, \"any\" soru/olumsuzdadır.",

// 2 Downtown – Şehirde
"## Şehirdeki Yerler\nbank, hospital, supermarket, park, library, police station, bakery, pharmacy.\n## Yön Sorma ve Tarif\n- Where is the bank? (Banka nerede?)\n- Go straight. (Düz git.)\n- Turn left. (Sola dön.) / Turn right. (Sağa dön.)\n- It's next to the park. (Parkın yanında.)\n- It's between the bank and the bakery. (Banka ile fırın arasında.)\n- It's opposite the school. (Okulun karşısında.)\n## Konum Edatları\nnext to (yanında), between (arasında), opposite (karşısında), in front of (önünde), behind (arkasında).\n💡 \"Turn\" dönmek, \"go straight\" düz gitmek; edatlar yer tarifinin anahtarıdır.",

// 3 Weather and Emotions – Hava ve Duygular
"## Hava Durumu\nsunny (güneşli), rainy (yağmurlu), windy (rüzgârlı), cloudy (bulutlu), snowy (karlı), hot, cold.\n- It's sunny today. (Bugün hava güneşli.)\n- What's the weather like? (Hava nasıl?)\n## Duygular\nhappy, sad, angry, tired, hungry, thirsty, scared, surprised.\n- How do you feel? (Nasıl hissediyorsun?)\n- I feel happy. / I'm tired.\n## Hava ile Duygu Bağlantısı\n- It's rainy, so I feel sad. (Yağmurlu, bu yüzden üzgünüm.)\n- It's sunny, so I'm happy. (Güneşli, bu yüzden mutluyum.)\n✏️ \"feel\" hissetmek; \"What's the weather like?\" ve \"How do you feel?\" kalıplarını ayırt et.",

// 4 Occupations – Meslekler
"## Meslekler\ndoctor (doktor), pilot, teacher (öğretmen), nurse (hemşire), police officer (polis), farmer (çiftçi), chef (aşçı), dentist (diş hekimi).\n## Meslek Sorma\n- What does she do? (O ne iş yapar?)\n- She is a doctor. (O bir doktor.)\n- What do you want to be? (Ne olmak istiyorsun?)\n- I want to be an engineer.\n## Çalışma Yerleri\n- A teacher works at a school.\n- A pilot works at an airport.\n- A chef works in a restaurant.\n## Meslek Tanımları\n- A doctor helps sick people.\n- A police officer catches thieves.\n💡 Meslek sorarken \"What does he/she do?\", kendin için \"What do you do?\" / \"I'm a student.\"",

// 5 Bookworms – Kitapkurtları
"## Kitap Türleri\nnovel (roman), comic (çizgi roman), fairy tale (masal), detective story (macera/polisiye), magazine (dergi).\n## Prefer (Tercih Etmek)\n- I prefer novels to comics. (Romanları çizgi romanlara tercih ederim.)\n- I prefer reading to watching TV.\n- Which do you prefer: books or comics? (Hangisini tercih edersin?)\n## Beğeni Sorma\n- What kind of books do you like? (Ne tür kitaplar seversin?)\n- Do you like adventure stories? Yes, I do. / No, I don't.\n## Kitap Önerisi\n- You should read this book. It's interesting.\n- I recommend this novel. (Bu romanı öneririm.)\n✏️ \"prefer A to B\" = A'yı B'ye tercih etmek; \"recommend\" önermek.",

// 6 Holidays – Tatiller
"## Simple Past (Geçmiş Zaman)\nGeçmişte bitmiş olaylar için kullanılır.\n- I visited my grandparents last summer. (Geçen yaz büyükannemi ziyaret ettim.)\n## Düzenli Fiiller (-ed)\nplay → played, visit → visited, watch → watched, stay → stayed.\n## Düzensiz Fiiller\ngo → went, see → saw, eat → ate, have → had, buy → bought, swim → swam.\n## Olumsuz ve Soru\n- Olumsuz: I didn't go to the beach. (didn't + fiilin yalın hâli)\n- Soru: Did you swim in the sea? → Yes, I did. / No, I didn't.\n## Tatil Kelimeleri\nbeach, sea, hotel, holiday, sunbathe, take photos, visit museums.\n💡 \"did\" zaten geçmiş anlamını verdiği için ana fiil yalın kalır: \"I didn't went\" değil \"I didn't go\".",

// 7 At the Fair – Panayırda
"## Present Continuous (Şimdiki Zaman)\nŞu anda olan eylemler için kullanılır: am/is/are + fiil-ing.\n- I am riding a bike. (Bisiklete biniyorum.)\n- She is eating cotton candy. (O pamuk şeker yiyor.)\n- They are playing games. (Onlar oyun oynuyorlar.)\n## -ing Kuralı\n- Ekle: play → playing, read → reading\n- E ile biten: make → making, ride → riding\n- Kısa ünlülü tek hece: sit → sitting, run → running\n## Panayır Kelimeleri\nferris wheel (dönme dolap), roller coaster, balloon, cotton candy, popcorn.\n## Şu An Yapılanlar\n- What are you doing? (Ne yapıyorsun?)\n- I'm having fun. (Eğleniyorum.)\n✏️ Şimdiki zaman \"şu an\" vurgusu yapar; \"now\", \"at the moment\" gibi kelimelerle kullanılır.",

// 8 Saving the Planet – Gezegeni Koruyalım
"## Çevre Sorunları\npollution (kirlilik), air pollution (hava kirliliği), plastic waste (plastik atık), deforestation (ormanların yok edilmesi), global warming (küresel ısınma).\n## Çözümler ve \"Should\"\nShould, öneri bildirir: \"...yapmalıyız\".\n- We should recycle paper. (Kâğıtları geri dönüştürmeliyiz.)\n- We shouldn't waste water. (Suyu israf etmemeliyiz.)\n- We should plant more trees.\n## Geri Dönüşüm\nrecycle (geri dönüştürmek), reuse (yeniden kullanmak), reduce (azaltmak).\n- 3R: Reduce, Reuse, Recycle.\n## Doğa Kelimeleri\nenvironment (çevre), nature, forest, ocean, energy, plastic bag.\n💡 should + fiil (yalın) öneridir; shouldn't = öneri + olumsuz.",

// 0 placeholder
],

/* ===================== DİN KÜLTÜRÜ ===================== */
din6: [
// 0 Peygamberlere ve İlahi Kitaplara İnanç
"## Peygamberlere İnanç\nPeygamberler, Allah'ın emir ve yasaklarını insanlara bildiren elçilerdir.\n- İnsanlara doğru yolu gösterir, örnek olurlar.\n- Son peygamber Hz. Muhammed'dir (s.a.v.).\n## İlahi Kitaplar\nAllah'ın vahiy yoluyla peygamberlerine gönderdiği kitaplardır.\n## Dört Büyük Kitap\n- Tevrat → Hz. Musa'ya\n- Zebur → Hz. Davut'a\n- İncil → Hz. İsa'ya\n- Kur'an-ı Kerim → Hz. Muhammed'e (s.a.v.)\n## Kutsal Kitap Özellikleri\n- Kur'an, son ilahi kitaptır ve kıyamete kadar korunmuştur.\n- İnsanlar için yol gösterici, doğruyu yanlıştan ayıran rehberdir.\n💡 Dört kitap ve peygamberlerini ezberle: Musa-Tevrat, Davut-Zebur, İsa-İncil, Muhammed-Kur'an.",

// 1 Namaz İbadeti
"## Namazın Önemi\nNamaz, İslam'ın beş şartından biridir; günde beş vakit kılınır.\n- Müslümanı kötülüklerden uzaklaştırır, düzen ve disiplin kazandırır.\n## Beş Vakit Namaz\nSabah, öğle, ikindi, akşam ve yatsı.\n## Namaza Hazırlık: Abdest\nEller, ağız, burun, yüz, kollar, baş ve ayakların yıkanmasıyla alınır; namazdan önce şarttır.\n- Abdestsiz namaz olmaz; temizlik imanın yarısı olarak görülür.\n## Namazın Farzları\n- Dışındaki şartlar (abdest, kıble, vakit, örtünme, niyet).\n- İçindeki şartlar (iftitah tekbiri, kıyam, kıraat, rükû, secde, oturma).\n## Namaz Çeşitleri\nFarz, vacip, sünnet ve nafile namazlar.\n✏️ Namaz kılınışı: niyet → tekbir → kıyam (ayakta Kur'an okuma) → rükû → secde → oturuş → selam.",

// 2 Zararlı Alışkanlıklar
"## Bağımlılık Nedir?\nBir madde ya da davranışın kişiyi kontrol altına alması ve bırakılamaması durumudur.\n## Bağımlılık Yapan Maddeler\nSigara, alkol, uyuşturucu ve teknoloji/oyun bağımlılığı.\n- Sigara: akciğer ve kalp hastalıklarına yol açar.\n- Alkol ve uyuşturucu: vücudu ve aklı bozar, aile ve topluma zarar verir.\n## Başlama Nedenleri\nArkadaş baskısı, merak, özenme ve sorunlardan kaçış.\n## Korunma Yolları\n- Hayır diyebilmek (kararlı olmak).\n- Zararlı ortamlardan uzak durmak.\n- Spor ve sanatla ilgilenmek, iyi arkadaşlar edinmek.\n💡 İlk deneme tehlikelidir; \"bir kereden bir şey olmaz\" yanlış inancı bağımlılığın kapısını açar.",

// 3 Hz. Muhammed'in Hayatı
"## Doğumu ve Çocukluğu\nHz. Muhammed (s.a.v.), 571 yılında Mekke'de doğdu.\n- Babası Abdullah, annesi Âmine'dir; annesi vefat edince büyükbabası ve amcası Ebu Talib baktı.\n- Küçük yaşta çobanlık yaptı, ticaretle uğraştı.\n## \"el-Emin\" (Güvenilir)\nDoğruluğu ve dürüstlüğüyle tanındı; toplum ona \"el-Emin\" (güvenilir) lakabını verdi.\n## Peygamberliği\n40 yaşında Hira Mağarası'nda ilk vahiy geldi (\"Oku\" emriyle Kur'an inmeye başladı).\n## İslam'a Daveti\nÖnce yakınlarını, sonra toplumu İslam'a çağırdı; baskılara rağmen davete devam etti.\n- Medine'ye hicret etti ve orada devletini kurdu.\n💡 Hz. Muhammed'in güvenilirliği (el-Emin), doğruluğu ve merhameti her Müslüman için örnektir.",

// 4 Temel Değerlerimiz
"## Doğruluk ve Dürüstlük\nDoğruyu söylemek, yalan ve hile yapmamaktır.\n- \"Doğru söyleyenin bir ayağı üzengide olmalı\" atasözü gibi, dürüstlük toplumda güven oluşturur.\n## Güvenilirlik\nSözünde durmak, emanete sahip çıkmak.\n## Yardımlaşma\nİhtiyaç sahibine el uzatmak; paylaşmak toplumsal dayanışmayı güçlendirir.\n## Hoşgörü ve Saygı\nFarklı görüş ve davranışlara karşı anlayışlı olmak, insanlara değer vermektir.\n- \"Kendin için istediğini başkası için de iste\" temel ahlak kuralıdır.\n✏️ Bu değerler yalnızca sözde değil; okulda, evde ve sokakta davranışa dönüşmelidir.",

// 5 Kur'an'da Akıl ve Bilgi
"## Akletmek ve Düşünmek\nKur'an, insanları düşünmeye, gözlem yapmaya ve akıllarını kullanmaya çağırır.\n- \"Hiç düşünmez misiniz?\" benzeri ayetler, aklın kullanılmasını ister.\n## Bilginin Önemi\n- \"Oku\" emri, Kur'an'ın ilk emridir.\n- Bilgili insanlar, bilmeyenlerle eşit değildir; ilim övülür.\n## Araştırma ve Öğrenme\nKur'an; evreni, gökyüzünü ve insanı incelemeyi teşvik eder.\n- Bilimsel gözlem, Kur'an'ın teşvik ettiği bir ibadet olarak görülür.\n## Öğütler\nDürüst olmak, adaletli davranmak, ilim öğrenmek ve öğretmek.\n✏️ Kur'an \"düşün\" der; bu yüzden bilim ve din, birbirine karşıt değil, destektir."
],

/* ===================== BİLİŞİM TEKNOLOJİLERİ ===================== */
bty6: [
// 0 Problem Çözme ve Algoritma
"## Problem Çözme\nProblemi tanıma, çözüm yolları üretme, en uygununu seçme ve uygulama sürecidir.\n1) Problemi anla, 2) Plan yap, 3) Çözümü uygula, 4) Sonucu değerlendir.\n## Algoritma\nBir problemi çözmek için izlenen adım adım sıralı adımlar bütünüdür.\n- \"Sabah kalkınca yapılanlar\" da bir algoritmadır: kalk → yüzünü yıka → kahvaltı → okula git.\n## Akış Şeması\nAlgoritmayı görselleştiren şekildir:\n- Başlangıç/bitiş: oval (elips)\n- İşlem: dikdörtgen\n- Karar (soru): baklava (elmas)\n- Oklar: akış yönü\n## Algoritma Yazarken Dikkat\nAdımlar kısa ve net olmalı; sıra doğru kurulmalı; sonuç kontrol edilmeli.\n💡 Aynı sonucu veren birden çok algoritma olabilir; en az adımlı ve anlaşılır olanı iyidir.",

// 1 Blok Tabanlı Programlama
"## Blok Tabanlı Araçlar\nScratch, Blockly, Code.org gibi araçlarla sürükle-bırak yöntemiyle programlanır.\n- Kod yazmak yerine bloklar birleştirilir; bu, programlama mantığını öğretir.\n## Döngüler\nAynı işlemi tekrar tekrar yaptırmak için kullanılır.\n- \"10 kere tekrarla\" bloğu: aynı hareketi 10 kez çalıştırır.\n- Sonsuz döngü: sürekli tekrar eder (karakterin sürekli yürümesi).\n## Koşullar (Karar Yapıları)\nBir şarta göre farklı işlemler yapılır.\n- \"Eğer ... ise ... değilse ...\" blokları.\n- Örnek: \"Eğer zeminin rengi kırmızıysa dur.\"\n## Olaylar\nBir olay (bayrağa tıklama, tuşa basma) programı başlatır veya tetikler.\n## Oyun ve Animasyon Yapımı\nKarakter, sahne, skor ve ses eklenerek oyun/anlık animasyonlar hazırlanır.\n✏️ Döngü = tekrar, koşul = karar. Oyunlarda skoru artırmak için döngü ve koşullar birlikte kullanılır.",

// 2 Kelime İşlemci İle Belgeler
"## Kelime İşlemci Programları\nWord, Google Docs, LibreOffice Writer gibi yazı belgeleri hazırlamaya yarar.\n## Biçimlendirme\n- Yazı tipi, boyut ve renk değiştirme.\n- Kalın (bold), italik, altı çizili.\n- Hizalama: sola, sağa, ortala, iki yana yasla.\n## Sayfa Düzeni\nKenar boşlukları, kağıt boyutu, yön (dikey/yatay).\n## Listeler ve Tablolar\n- Madde işaretli ve numaralı listeler.\n- Tablolarla bilgiyi satır-sütun düzeninde gösterme.\n## Yazdırma\nÖnizleme yapmak, kopya sayısını ayarlamak ve yazıcıya göndermek.\n💡 Başlıklar için stil kullan (Başlık 1, Başlık 2); metni seçip tek tuşla biçimlendirirsin.",

// 3 Elektronik Tablolama
"## Elektronik Tablo Programları\nExcel, Google Sheets, LibreOffice Calc gibi programlardır.\n## Hücre Kavramı\n- Satır (1, 2, 3...) ve sütunların (A, B, C...) kesiştiği yerlere hücre denir.\n- Hücre adresi: sütun+satır (örn. B5).\n## Veri Girişi\nHücrelere sayı, metin veya tarih girilir.\n## Formüller\nFormül \"=\" ile başlar:\n- =A1+B1 (toplama)\n- =SUM(A1:A5) (aralık toplamı)\n- =A2*B2 (çarpma)\n## Grafikler\nVeri seçilir ve sütun, çizgi veya pasta grafiğe dönüştürülür.\n- Grafik, veriyi görsel ve hızlı yorumlamayı sağlar.\n💡 Formül hücrede görünmez; sonuç gösterilir. Otomatik hesaplama elektronik tablonun gücüdür.",

// 4 Sunum Becerileri
"## Sunum Programları\nPowerPoint, Google Slides, Canva gibi araçlarla slaytlar hazırlanır.\n## Etkili Slayt İlkeleri\n- Az yazı, çok görsel kullan.\n- Başlık kısa ve net olsun.\n- Font büyüklüğü yeterli (en az 24 punto civarı) ve okunaklı olsun.\n- Gereksiz animasyonlarla dikkati dağıtma.\n## Slayt Düzeni\nBaşlık, metin, görsel ve grafik alanlarının dengeli yerleşimi.\n## Animasyon ve Geçişler\n- Slayt geçişleri: slayttan slayta geçerken.\n- Animasyonlar: öğelerin (yazı, resim) giriş/çıkış hareketleri.\n## Sunum Teknikleri\nİzleyiciyle göz teması, yüksek ve net ses, konuya hâkimiyet, zamanı yönetme.\n✏️ Slayt süs değil, anlatımı destekleyen araçtır; en etkili sunum izleyiciyi bilgilendiren ve ilgi çeken sunumdur.",

// 5 Dijital Vatandaşlık ve Güvenlik
"## Dijital Vatandaşlık\nDijital dünyada hak ve sorumluluklarını bilerek, saygılı ve güvenli davranmaktır.\n## Parola Güvenliği\n- Güçlü parola: uzun, büyük-küçük harf + rakam + sembol içerir.\n- Parolayı kimseyle paylaşma; farklı hesaplara farklı parola kullan.\n## Dijital Haklar ve Sorumluluklar\nBaşkasına ait içeriği izinsiz kullanma; kişisel bilgileri koru.\n## Telif Hakları\nYazı, müzik, görsel gibi eserlerin sahibinin izni olmadan kopyalanıp kullanılamamasıdır.\n- Kaynak göstermek (alıntı) kuralı.\n## Güvenli Paylaşım\nAdres, okul, telefon gibi özel bilgileri internette paylaşma.\n- Tanımadığın kişilerin mesajlarına dikkat et; şüpheli bağlantılara tıklama.\n💡 İnternette yazdığın her şey kalıcıdır; paylaşmadan önce iki kez düşün.",

// 6 İletişim ve İş birliği Araçları
"## E-Posta\nElektronik posta; mesaj, dosya ve resim göndermek için kullanılır.\n- Adres yapısı: kullanıcıadı@alanadı (örn. ali@ornek.com).\n- Konu (subject) yazmak, dosya eklemek ve alıcıyı doğru yazmak önemlidir.\n## Dosya Paylaşımı\nBulut depolama (Google Drive, OneDrive) ile dosyalar link üzerinden paylaşılır.\n- Linkin erişim ayarını (yalnızca davetliler) kontrol et.\n## İş birliği Araçları\nGoogle Docs, Canva gibi araçlarla aynı belgeyi birlikte düzenlemek.\n- Yorum ve öneri yaparak birlikte çalışma.\n## Görgü Kuralları (Netiket)\n- Büyük harfle yazma (bağırmak gibidir), kısa ve saygılı ol.\n- Karşındakinin mesajına uygun sürede cevap ver.\n- İzin almadan kişisel bilgi ve fotoğraf paylaşma.\n✏️ E-postada gönder (send) tuşuna basmadan önce alıcı, konu ve ekleri kontrol et.",

// 7 Arama Motorları ve Bilgiye Erişim
"## Arama Motorları\nGoogle, Bing, Yandex gibi araçlar internette bilgiyi bulmaya yarar.\n## Etkili Anahtar Kelime\n- Kısa ve anlamlı anahtar kelimeler kullan: \"Türkiye'nin başkenti\" gibi.\n- Uzun sorular yerine birkaç anahtar kelime daha iyi sonuç verir.\n## Bilginin Doğruluğunu Sorgulama\nİnternetteki her bilgi doğru olmayabilir.\n- Kaynağı kontrol et: resmî kurumlar (.gov, .edu, .k12) ve tanınmış kuruluşlar güvenilirdir.\n- Aynı bilgiyi birden çok kaynaktan doğrula.\n## Güvenli Arama\n- Güvenli arama modunu aç.\n- Reklam sonuçları ile gerçek sonuçları ayırt et.\n- Şüpheli sitelerden ve dosya indirmelerinden kaçın.\n💡 Bilgiyi bulmak kadar, onu doğrulamak da bir beceridir; tek kaynağa güvenme."
],

/* ===================== ALMANCA ===================== */
alm6: [
// 0 Begrüßung – Selamlaşma
"## Selamlaşma\n- Hallo! (Merhaba!)\n- Guten Morgen! (Günaydın!)\n- Guten Tag! (İyi günler!)\n- Guten Abend! (İyi akşamlar!)\n## Kendini Tanıtma\n- Ich heiße Eymen. (Benim adım Eymen.)\n- Wie heißt du? (Senin adın ne?)\n- Ich komme aus der Türkei. (Türkiye'den geliyorum.)\n## Nasılsın?\n- Wie geht es dir? (Nasılsın?)\n- Mir geht es gut. (Ben iyiyim.)\n- Mir geht es schlecht. (Ben kötüyüm.)\n## Soru Kelimeleri\n- Wie? (Nasıl?), Wo? (Nerede?), Wer? (Kim?), Was? (Ne?)\n✏️ Almanca isimler büyük harfle başlar: \"guten Morgen\" değil \"Guten Morgen\".",

// 1 Zahlen – Sayılar
"## Sayılar 1-20\neins (1), zwei (2), drei (3), vier (4), fünf (5), sechs (6), sieben (7), acht (8), neun (9), zehn (10)\nelft (11), zwölf (12), dreizehn (13), vierzehn (14), fünfzehn (15), sechzehn (16), siebzehn (17), achtzehn (18), neunzehn (19), zwanzig (20).\n## Onlular (20-100)\nzwanzig (20), dreißig (30), vierzig (40), fünfzig (50), sechzig (60), siebzig (70), achtzig (80), neunzig (90), hundert (100).\n- 21 → einundzwanzig (1 ve 20: \"einundzwanzig\")\n- 35 → fünfunddreißig (5 ve 30: \"fünfunddreißig\")\n## Yaş Sorma\n- Wie alt bist du? (Kaç yaşındasın?)\n- Ich bin zwölf Jahre alt. (12 yaşındayım.)\n## Alışverişte Sayılar\nFiyatlar: \"Das kostet fünf Euro.\" (Bu 5 euro eder.)\n💡 Almanca'da birler önce söylenir: 23 → dreiundzwanzig (3 ve 20).",

// 2 Farben – Renkler
"## Renkler\nrot (kırmızı), blau (mavi), grün (yeşil), gelb (sarı), schwarz (siyah), weiß (beyaz), grau (gri), braun (kahverengi), orange (turuncu), pink (pembe).\n## Renk Sorma\n- Welche Farbe ist das? (Bu hangi renk?)\n- Das ist rot. (Bu kırmızı.)\n## Was ist das?\n- Was ist das? (Bu nedir?)\n- Das ist ein rotes Auto. (Bu kırmızı bir araba.)\n## Nesneleri Betimleme\nRenk, isimden önce gelir ve isimle uyum sağlar.\n- der rote Ball (kırmızı top), die blaue Tasche (mavi çanta), das grüne Buch (yeşil kitap).\n✏️ Almanca renkler çoğu zaman İngilizce'ye benzer: rot≈red, blau≈blue, grün≈green — hızlı öğrenilir.",

// 3 Meine Familie – Ailem
"## Aile Üyeleri\ndie Mutter (anne), der Vater (baba), die Eltern (anne-baba), die Schwester (kız kardeş), der Bruder (erkek kardeş), die Geschwister (kardeşler), die Großmutter (büyükanne), der Großvater (büyükbaba).\n## Aileyi Tanıtma\n- Das ist meine Mutter. (Bu benim annem.)\n- Das ist mein Vater. (Bu benim babam.)\n- Ich habe eine Schwester. (Bir kız kardeşim var.)\n- Ich habe zwei Brüder. (İki erkek kardeşim var.)\n## Artikel (Tanımlık)\nAlmanca isimlerin tanımlıkları vardır: der (eril), die (dişil), das (nötr).\n- der Vater, die Mutter, das Kind (çocuk).\n💡 Aile tanıtırken \"mein/meine\" (benim) kullanılır: mein Vater, meine Mutter.",

// 4 Die Schulsachen – Okul Eşyaları
"## Okul Eşyaları\n- der Stift (kalem), der Kugelschreiber (tükenmez kalem), der Bleistift (kurşun kalem)\n- das Buch (kitap), das Heft (defter), das Lineal (cetvel)\n- die Schultasche (okul çantası), der Ranzen (okul çantası), die Schere (makas)\n## Artikel Sorusu\n- Was ist das? → Das ist ein Buch.\n- \"der\" için ein, \"die\" için eine, \"das\" için ein.\n## Sahip Olma\n- Ich habe einen Ranzen. (Bir çantam var.)\n## Sınıfta\n- der Tisch (masa), der Stuhl (sandalye), die Tafel (tahta), das Klassenzimmer (sınıf).\n✏️ Artikeli öğrenmeden ismi öğrenme: \"Buch\" değil \"das Buch\" diye ezberle.",

// 5 Hobbys und Freizeit – Hobiler
"## Boş Zaman Aktiviteleri\n- Sport treiben (spor yapmak), Fußball spielen (futbol oynamak), Musik hören (müzik dinlemek), lesen (okumak), schwimmen (yüzmek), zeichnen (resim çizmek).\n## Ich spiele...\n- Ich spiele Fußball. (Futbol oynarım.)\n- Ich spiele Klavier. (Piyano çalarım.)\n- Ich höre Musik. (Müzik dinlerim.)\n## Hobi Sorma\n- Was machst du in deiner Freizeit? (Boş zamanında ne yaparsın?)\n- Was sind deine Hobbys? (Hobilerin neler?)\n- Mein Hobby ist Lesen. (Hobim okumak.)\n✏️ \"spielen\" oynamak/çalmak: Ich spiele Fußball, Ich spiele Klavier; \"hören\" dinlemek.",

// 6 Essen und Trinken – Yeme İçme
"## Yiyecek ve İçecekler\ndas Brot (ekmek), der Käse (peynir), die Butter (tereyağı), das Ei (yumurta), das Wasser (su), die Milch (süt), der Saft (meyve suyu), der Tee (çay), der Kaffee (kahve).\n## Kahvaltı\n- das Frühstück (kahvaltı)\n- Ich esse Brot mit Käse. (Ekmekle peynir yerim.)\n- Ich trinke Milch. (Süt içerim.)\n## İstek Bildirme: Ich möchte...\n- Ich möchte ein Glas Wasser. (Bir bardak su istiyorum.)\n- Ich möchte bitte einen Tee. (Lütfen bir çay istiyorum.)\n- Ich hätte gern ein Brot. (Bir ekmek istiyorum.)\n## Sipariş Verme\n- Was möchtest du? (Ne istersin?)\n- Ich möchte ein Stück Kuchen. (Bir dilim kek istiyorum.)\n✏️ \"möchte\" = istemek (nazik istek); \"essen\" yemek, \"trinken\" içmek.",

// 7 Die Tiere – Hayvanlar
"## Evcil Hayvanlar\nder Hund (köpek), die Katze (kedi), der Vogel (kuş), der Fisch (balık), das Kaninchen (tavşan), die Maus (fare).\n## Hayvanat Bahçesi\n- der Löwe (aslan), der Elefant (fil), der Affe (maymun), der Bär (ayı), die Giraffe (zürafa).\n## Hayvan Betimleme\n- Der Hund ist braun. (Köpek kahverengidir.)\n- Die Katze ist klein und süß. (Kedi küçük ve tatlıdır.)\n## Sahip Olma (haben)\n- Ich habe einen Hund. (Bir köpeğim var.)\n- Ich habe eine Katze. (Bir kedim var.)\n- Hast du ein Haustier? (Evcil hayvanın var mı?)\n💡 Hayvanlarda da artikel var: der Hund, die Katze, das Kaninchen; betimlemede renk kelimelerini kullan."
]

};

if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) {
      if (dt[i] && !b.detay) b.detay = dt[i];
    });
  });
}


/* ==== Yeni seçmeli ders notları (otomatik eklendi) ==== */

DETAY6["grs6"] = ["## Renk Çemberi\nAna renkler kırmızı, sarı ve mavidir; başka renkten üretilemez.\n- Ara renkler iki ana rengin karışımıdır: yeşil (sarı+mavi), turuncu (kırmızı+sarı), mor (kırmızı+mavi).\n- Sıcak renkler (kırmızı, turuncu, sarı) enerji ve sıcaklık hissi verir.\n- Soğuk renkler (mavi, yeşil, mor) sakinlik ve serinlik hissi verir.\n## Ton Kavramı\n- Aynı rengin açık ve koyu hâlleri tondur. Beyaz katılırsa açık ton, siyah katılırsa koyu ton oluşur.\n- Degrade, rengin koyudan açığa yumuşak geçişidir.\n## Tamamlayıcı Renkler\n- Renk çemberinde karşılıklı duran renkler tamamlayıcıdır: kırmızı-yeşil, sarı-mor, mavi-turuncu.\n- Yan yana kullanıldıklarında birbirini güçlendirir, canlılık sağlar.\n💡 Boya karıştırırken azar az ekle: koyuya açık eklemek kolay, açığa koyu eklemek zordur.","## Temel Malzemeler\n- Kurşun kalem sertlikleri: H sert ve açık, HB orta, B serisi (2B, 4B, 6B) yumuşak ve koyu.\n- Silgi ile hem hata silinir hem de açık ton efekti yapılabilir (çekme tekniği).\n## Tonlama\n- Formu (hacmi) kazandırmak için ışık-gölge kullanılır: ışık alan yüz açık, gölgede kalan yüz koyu çizilir.\n- Tarama (paralel çizgiler), haç tarama (çapraz çizgiler) ve noktacılıkla ton elde edilir.\n## Çizime Başlama\n- Önce hafif hatlarla büyük şekilleri yerleştir, ayrıntıları sona bırak.\n- Hatalı çizgiyi hemen silme; doğru hat üzerine çalış.\n💡 Nesneye gözlerini kısarak bak; açık-koyu farklar daha net görünür.","## Perspektif\n- Uzak nesneler küçük, yakın nesneler büyük görünür; paralel çizgiler ufukta bir noktada birleşir: kaçış noktası.\n- Tek kaçış noktalı perspektifte önce göz hizası (ufuk çizgisi) çizilir; yol, cadde ve koridor çizimlerinde idealdir.\n## Kompozisyon\n- Resmin öğelerinin sayfa üzerindeki düzenine kompozisyon denir.\n- Ana konu boşluklarla dengelenmeli; tüm öğeler bir köşeye yığılmamalı.\n- Üçler kuralı: sayfayı dikey ve yatayda üçe böl; ilgi noktalarını kesişimlere yerleştir.\n## Orantı ve Simetri\n- Orantı nesnelerin birbirine boyut ilişkisi, simetri ise bir eksene göre aynılıktır.\n💡 Önce küçük bir ön çizim (taslak) yap; kompozisyonu kenarda dene."];
if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) { if (dt[i]) b.detay = dt[i]; });
  });
}

DETAY6["mzk6"] = ["## Ritim\n- Ritim, seslerin ve sessizliklerin zamana göre düzenli akışıdır. Kalp atışı gibi düzenli vuruşlara nabız denir.\n- Ölçü, ritmin gruplandığı eşit bölmelerdir; aralarına ölçü çizgisi çizilir.\n## Tempo\n- Tempo parçanın hızıdır: Largo (çok yavaş), Adagio (yavaş), Andante (yürüyüş hızında), Allegro (hızlı), Presto (çok hızlı).\n- Metronom, tempoyu sabit tutmak için kullanılır.\n## Sus İşaretleri\n- Sessizlik de müziğin parçasıdır; sus işaretleri nota değerleri kadar süre sessiz kalınacağını gösterir.\n💡 Ritmi tutmak için şarkıyı mırıldanırken ayağın ya da elinle düzenli vuruş yap.","## Nota\n- Nota, sesin yüksekliğini ve süresini gösteren işarettir.\n- Temel sesler: do, re, mi, fa, sol, la, si. Bir oktavda 7 temel ses vardır.\n- Porte beş çizgi ve dört aralıktan oluşur; notaların yüksekliği sesin incelik-kalınlığını gösterir.\n## Nota Değerleri\n- Tam nota 4 vuruş, yarım nota 2 vuruş, çeyrek nota 1 vuruş sürer.\n## Solfej\n- Solfej, sesleri doğru yükseklikte ve sürede söyleme çalışmasıdır. Önce yavaş tempoda oku, sonra hızlandır.\n💡 Yeni parçayı önce ritmini elinle vurarak çalış; sonra seslere geçmek çok kolaylaşır.","## Çalgı Grupları\n- Telli: keman, gitar, ud, kanun. Ses tellerin titreşmesiyle oluşur.\n- Üflemeli: flüt, klarnet, trompet, zurna. Ses havanın titreşmesiyle oluşur.\n- Vurmalı: davul, def, zil. Ses çarpma ile oluşur.\n## İnsan Sesi\n- İnsan sesi de bir çalgıdır; nefes kontrolü ile güçlenir.\n- Doğru nefes: diyaframı kullanmak, omuzları kaldırmadan derin almak.\n## Dinleme Kültürü\n- Farklı türlerden müzik dinlemek müzikal kulağı geliştirir.\n💡 Gözlerini kapayıp bir çalgının sesini dinle ve hangi grup olduğunu tahmin et."];
if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) { if (dt[i]) b.detay = dt[i]; });
  });
}

DETAY6["bed6"] = ["## Neden Isınırız?\n- Isınma kalp atışını ve vücut ısısını yavaşça yükseltir; kaslara kan gitmesini sağlar.\n- Isınmayan kas gerilmelere ve sakatlanmalara açıktır.\n## Nasıl Isınırız?\n- 5-10 dakika hafif tempo koşu, yerinde koşu, ip atlama.\n- Eklem çevirme: boyun, omuz, kol, bel, diz, ayak bileği.\n## Esnetme\n- Statik esnetme: pozisyonu zıplamadan 15-30 saniye sabit tutmak.\n- Hafif gerginlik normaldir ama ağrı olmamalıdır.\n- Spordan sonra soğuma ve esnetme yapılır; nabız yavaş yavaş düşer.\n💡 Kural: Isınmadan maç olmaz, maçtan sonra soğuma olmadan antrenman bitmez.","## Temel Oyun Kuralları\n- Futbol: 11'er oyuncu, top elle oynanmaz (kaleci hariç), iki devre.\n- Basketbol: 5'er oyuncu, top elde koşulamaz (sürülür), sayı potaya sokulur.\n- Voleybol: 6'şar oyuncu, topa en fazla üç dokunuş, file üzerinden karşı sahaya.\n- Hentbol: 7'şer oyuncu, üç adama kadar top elde taşınabilir.\n## Takım Ruhu\n- Pas paylaşımı, pozisyon alma ve birbirini destekleme oyundan alınan keyfi artırır.\n- Hakem kararlarına saygı fair-play'in temelidir.\n💡 Kazanmak kadar önemli: kurallara uymak ve rakibe saygı göstermek.","## Dengeli Beslenme\n- Öğün atlamamak en önemlisidir: kahvaltı, öğle ve akşam düzenli olmalı.\n- Tabakta çeşitlilik: sebze-meyve, tahıl, süt ürünleri, et/baklagil.\n## Su\n- Günde en az 6-8 bardak su; spor yapılan günlerde daha fazlası.\n- Susuzluk baş ağrısı, yorgunluk ve dikkatsizliğe yol açar.\n## Spor ve Enerji\n- Karbonhidratlar (ekmek, makarna, bulgur) temel enerji kaynağıdır.\n- Proteinler (et, yumurta, baklagil) kas onarımı için gerekir.\n- Spordan hemen önce ağır ve yağlı yemekten kaçın.\n💡 En iyi içecek sudur; şekerli gazlı içecekler kısa enerji patlaması sonra çöküş yaratır."];
if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) { if (dt[i]) b.detay = dt[i]; });
  });
}

DETAY6["tvt6"] = ["## Aşamalar\n1. İhtiyaç/Problem: Hangi sorunu çözüyorum?\n2. Araştırma: Benzer ürünler sorunu nasıl çözüyor?\n3. Fikir Üretme: Beyin fırtınasıyla çok sayıda alternatif.\n4. Prototip: Eskiz çiz, basit model üret.\n5. Test ve Değerlendirme: Dene, hataları bul, iyileştir.\n6. Sunum: Sürecini ve ürününü tanıt.\n## Tasarım Defteri\n- Her adımı tarih ve çizimlerle kaydet; sunumda en büyük yardımcın olur.\n## Beyin Fırtınası Kuralları\n- Eleştiri yok, tuhaf fikirler serbest, nicelik önemli, fikirler üzerine inşa edilir.\n💡 İlk fikrin en iyisi olmak zorunda değil; test edip geliştirmek tasarımın kendisidir.","## Basit Makineler\nİşi kuvvetten veya zamandan kazandıran temel düzeneklerdir.\n- Kaldıraç: dayanak noktası etrafında dönerek kuvvet iletir (makas, pense, tahterevalli).\n- Makara: ip ve çark ile yükü kaldırır, kuvvetin yönünü değiştirir (bayrak direği, kuyu makarası).\n- Eğik düzlem (rampa): yükü kaydırarak kaldırmayı kolaylaştırır (yokuş, merdiven).\n- Tekerlek ve aks: dönme hareketiyle taşıma sağlar.\n- Vida: eğik düzlemin mil etrafına sarılmış hâlidir.\n## Günlük Yaşam\n- Kapı kolu, makas, fındık kıracağı ve bisiklet; hepsi basit makinelerin birleşimidir.\n💡 Evdeki bir düzeneği seç; hangi basit makine(ler)den oluştuğunu bulmaya çalış.","## Atık Türleri\n- Geri dönüştürülebilir: kâğıt-karton, cam, metal, bazı plastikler.\n- Organik atık: yemek ve bahçe artıkları; kompost yapılabilir.\n- Özel (tehlikeli) atık: pil, elektronik, ilaç; ayrı toplama noktalarına gider.\n## Geri Dönüşüm Süreci\n- Ayrıştırma → Toplama → İşleme → Yeni ürün. Sembolü üçgen içinde oklardır.\n## Neden Önemli?\n- Doğal kaynakları korur, enerji tasarrufu sağlar, çöp alanlarının dolmasını geciktirir.\n- Alüminyum kutunun geri dönüşümü, sıfırdan üretime göre %95'e varan enerji tasarrufudur.\n💡 Okulda ya da evde ayrıştırma kutusu kur: az tüket, tekrar kullan, geri dönüştür."];
if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) { if (dt[i]) b.detay = dt[i]; });
  });
}

DETAY6["reb6"] = ["## Temel Duygular\n- Sevinç, üzüntü, korku, öfke, sürpriz ve iğrenme evrenseldir; hepsinin bir görevi vardır.\n- 'Kötü duygu' yoktur; zor duygular da bizi korur (korku tehlikeden, öfke haksızlığa tepki verdirir).\n## Duyguyu Fark Etme\n- Beden sinyallerine dikkat: sıkışan boğaz, hızlanan kalp, yumruk sıkma.\n- Duygu günlüğü tutmak fark etmeyi kolaylaştırır.\n## Sağlıklı İfade\n- 'Ben dili' kullan: suçlamayan cümlelerle 'Üzüldüm çünkü...' şeklinde anlat.\n- Zorlandığında güvenilir bir yetişkinle konuşmak güçlülüktür, zaafiyet değil.\n## Stresle Başa Çıkma\n- Derin nefes (4 al, tut, 4-6 ver), yürüyüş, su içmek, sevdiğin bir iş.\n💡 Öfkelendiğinde 10'a kadar say ve nefes al; sakin beyin daha iyi karar verir.","## Sağlıklı Arkadaşlık\n- Karşılıklı güven, saygı, dürüstlük ve destek temeldir.\n- Sınırlara saygı: 'hayır' diyebilmek ve karşıdakinin 'hayır'ını kabul edebilmek.\n## Empati\n- Empati, kendini karşındakinin yerine koyup duygusunu anlamaktır.\n- 'Onun yerine olsam ne hissederdim?' sorusu empatiyi geliştirir.\n## Çatışma Çözümü\n- Sakinleş → dinle → duygunu ben diliyle söyle → birlikte çözüm ara.\n- Küsmek, dedikodu ve dışlamak sorunu çözmez, büyütür.\n## Zorbalık\n- Alay, dışlama ve fiziksel zorbalığa tanık olduğunda bir yetişkine haber ver.\n💡 İyi bir arkadaş olmak, iyi arkadaşlar bulmanın en hızlı yoludur.","## Akıllı Hedef (SMART)\n- Belirli, ölçülebilir, ulaşılabilir, gerçekçi ve zamanlı olsun: 'Ay sonuna kadar 20 yeni kelimeyi çalışıp diktede yazacağım.'\n## Büyük Hedef → Küçük Adımlar\n- Büyük hedefi haftalık ve günlük küçük görevlere böl; her tamamlanan adım motivasyonu artırır.\n## Plan Yapma\n- Akşamdan ertesi günün listesini hazırla; önce en zor işi bitir.\n- 25-30 dakika çalış, 5 dakika mola ver.\n## Erteleme ile Başa Çıkma\n- '5 dakika başlarım' kuralı: başlamak en zoru, devamı kendiliğinden gelir.\n- Telefonu ve oyunu başka odaya koy.\n💡 Hedefe ulaşınca kendini ödüllendir ve yeni hedef belirle; başarı sprint değil maratondur."];
if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) { if (dt[i]) b.detay = dt[i]; });
  });
}

/* ==== TYMM6 güncellemesi ==== */
delete DETAY6['trk6'];
delete DETAY6['mat6'];
delete DETAY6['fen6'];
delete DETAY6['sos6'];
delete DETAY6['ing6'];
delete DETAY6['alm6'];
delete DETAY6['din6'];
delete DETAY6['bty6'];
delete DETAY6['grs6'];
delete DETAY6['mzk6'];
delete DETAY6['bed6'];
if (typeof MUFREDAT !== 'undefined' && MUFREDAT['6']) {
  MUFREDAT['6'].dersler.forEach(function (d) {
    var dt = DETAY6[d.id];
    if (!dt) return;
    d.birimler.forEach(function (b, i) { if (dt[i] && !b.detay) b.detay = dt[i]; });
  });
  MUFREDAT['6'].dersler.forEach(function (d) {
    d.birimler.forEach(function (b) {
      if (b.ad.indexOf('📝') !== -1 || b.ad.indexOf('📋') !== -1) delete b.detay;
    });
  });
}
